[supervisord]
nodaemon=true
logfile=/dev/stdout
childlogdir=/var/log

[program:scraper]
command=python scraper_worker.py
autorestart=true
priority=5

[program:listener]
command=python sync_listener.py
autorestart=true
priority=10
